# Numpy Practices
### Shyam Sundhar G

In [2]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

## Creating Numpy Arrays

In [3]:
arr1=np.array([1,2,5],dtype=np.int32)
arr1

array([1, 2, 5], dtype=int32)

In [4]:
# Creating 2 D Array
ogarr=np.array([[1,2,3],[7,8,9]])
ogarr

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
# Creating 3 D Array
ogarr1=np.array([[[1,2],[5,6],[5,9]]])
ogarr1

## Linspace Command

In [ ]:
linarr=np.linspace(0,5,8)
linarr

In [ ]:
linarr=np.linspace(0,8,5) # 0 => start 8 => end 2=> no of elements
linarr

## Logspace Command

In [ ]:
logarr=np.logspace(0,5,8) # 0 => start 8 => end 2=> no of elements
logarr

## Arange Command

In [ ]:
ranarr=np.arange(0,50,2) # 0=> Start 50=> Stop 2=> Step
ranarr

## Zero Matrix

In [ ]:
zeroarr=np.zeros(3)
zeroarr

In [ ]:
zeroarr1=np.zeros((3,3))
zeroarr1

In [ ]:
zerolikearr= np.zeros_like(ogarr) # Create a Zero matrix with the shape of given array
zerolikearr

## Ones Matrix

In [ ]:
onearr=np.ones(3)
onearr

In [ ]:
onearr1=np.ones((3,3))
onearr1

In [ ]:
onelikearr= np.ones_like(ogarr) # Create a Ones matrix with the shape of given array
onelikearr

# 2 - Array Inspection

## Array Dimension and Shapes

In [ ]:
arrd=np.array([1,2,3])
print(f"Dimension: {arrd.ndim} , Shape: {arrd.shape} , Size: {arrd.size}")

## Array Indexing and Slicing

In [ ]:
arrindexsli = np.array([10, 20, 30, 40, 50])
fele=arrindexsli[0]
thrdele=arrindexsli[2]
lastele=arrindexsli[-1]
print(f'''
First Element : {fele}
Second Element : {lastele}
Last Element : {lastele}
''')

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sliarr=arr2d[0,1]
sliarr

In [ ]:
sliarr1=arr2d[1,1]
sliarr1

In [ ]:
sliarr2=arr2d[0,2]
sliarr2

In [ ]:
slicin=arr2d[1:4]
slicin

In [ ]:
slicin=arr2d[0::2]
slicin

In [ ]:
slicin=arr2d[-2::]
slicin

In [ ]:
slicin=arr2d[arr2d>5]
slicin

In [ ]:
slicin=arr2d[1:3,0:2]
slicin

# 3 Array Operations

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([5,8,7])
sca=2

res=arr1+arr2
res

In [ ]:
res=arr1 - arr2
res

In [ ]:
res=arr1 * arr2
res

In [ ]:
res=arr1 / arr2
res

## Matrix Operations

In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

res = matrix1+matrix2
res

In [ ]:
res = matrix1-matrix2
res

In [ ]:
res = matrix1*matrix2
res

In [ ]:
res = matrix1/matrix2
res

In [ ]:
matrixmul=np.dot(matrix1,matrix2)
matrixmul

In [ ]:
matrix=matrix1*sca

matrix

## Append and Delete

In [ ]:
ogarr=np.append(ogarr,[4,5,6])
ogarr

In [ ]:
newarr=np.delete(ogarr,2)
newarr

In [ ]:
newarr = np.delete(ogarr, 1, axis=0) # 0=> Row 1=> Column
newarr

## Aggregation Functions

In [ ]:
meanval=np.mean(ogarr)
medianval=np.median(ogarr)
stddev=np.std(ogarr)
sumval=np.sum(ogarr)
minval=np.min(ogarr)
maxval=np.max(ogarr)
sqrtarr=np.sqrt(ogarr)
exparr=np.exp(ogarr)

print(f'''
Mean : {meanval}
Median : {medianval}
Standard Deviation : {stddev}
Sum Value : {sumval}
Minimum Value : {minval}
Maximum Value : {maxval}

Square Root : {sqrtarr}

Exponential : {exparr}
''')

## Reshaping Arrays

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

arr1d=arr2d.reshape(6)
arr1d

In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])

arr_2d = arr_1d.reshape(2, 3)
arr_2d

## Working with Skimage Library

In [ ]:
from skimage import data
image=data.coins()

print("Original Image Shape : ",image.shape)

reimage=image.reshape(-1)

print("Reshaped Image Shape : ",reimage.shape)

# Working with Numpy Arrys

## Concatenation

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

com = np.concatenate((arr1, arr2)) 
com

In [ ]:
vsta = np.vstack((arr1, arr2))
vsta

In [ ]:
hsta = np.hstack((arr1, arr2))
hsta

## Splitting Arrays

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

sparr = np.split(arr, 3)
sparr

## Alias Command

In [ ]:
origrr = np.array([1, 2, 3])

alarr = origrr

alarr[0]=10

origrr

## View Command

In [ ]:
original_arr = np.array([1, 2, 3])

view_arr = original_arr.view()
view_arr[0] = 99
print(original_arr)

## Copy Command

In [ ]:
original_arr = np.array([1, 2, 3])


copy_arr = original_arr.copy()
copy_arr[0] = 100

print(original_arr)

## Sorting Numpy Arrays

In [ ]:
data = np.array([3, 1, 5, 2, 4])

sorted_data = np.sort(data) 
print("Ascending sort", sorted_data)
reverse_sorted_data = np.sort(data)[::-1] 
print("Descending sort", reverse_sorted_data)

sorted_indices = np.argsort(data)
print("Sorted Indices", sorted_indices)

# Numpy for Data Cleaning

## Identify the Missing Values

In [ ]:
arr = np.array([1, 2, np.nan, 4, np.nan, 6])
hasmiss = np.isnan(arr)
print(hasmiss)

## Removing rows or columns with Missing Values

In [ ]:
arr = np.array([[1, 2, 3], [4, np.nan, 6], [7, 8, 9]])

cleaned_data = arr[~np.any(np.isnan(arr), axis=1)]
print(cleaned_data) 

# Numpy for Statistical Analysis

## Data Transformation

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
mean = np.mean(arr)
centered_data = arr - mean
print('Centered data = ',centered_data)

std_dev = np.std(arr)
standardized_data = (arr - mean) / std_dev
print("standardized data = ",standardized_data)

log_transformed_data = np.log(arr)
print("log_transformed_data = ",log_transformed_data)

## Random Sampling and Generation

In [5]:
rarr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
random_samples = np.random.choice(rarr, size=5, replace=False)
random_samples

array([6, 7, 9, 2, 3])

In [8]:
num_samples = 1000
bootsamples = np.random.choice(rarr, size=(num_samples, len(rarr)), replace=True)
bootsamples

array([[ 4, 10,  4, ...,  2,  6,  5],
       [ 1,  3,  7, ...,  8,  6,  7],
       [ 3, 10,  5, ...,  3,  1,  3],
       ...,
       [ 4,  7,  8, ..., 10,  9,  6],
       [ 9, 10,  3, ...,  8,  6,  8],
       [ 8,  9,  9, ...,  4,  1,  5]])

## Generation

In [9]:
np.random.randint(0,100)

11

In [10]:
mean = 0
stddev = 1
normval = np.random.normal(mean, stddev, 5)
print(normval)

[ 0.10519804 -0.45367959  1.07539575 -0.49289178  0.31136852]


In [11]:
n_trials = 10
probability = 0.5
binovalues = np.random.binomial(n_trials, probability, 5)
print(binovalues)

[4 4 5 6 7]


In [12]:
rate = 2.5
poisson_values = np.random.poisson(rate, 5)
print(poisson_values)

[3 2 2 1 3]


In [13]:
scale_parameter = 0.5
exponentialvalues = np.random.exponential(scale_parameter, 5)
print(exponentialvalues)

[0.03460804 0.68475213 2.26000121 0.43005405 0.84729542]


In [14]:
mean_of_log = 0
std_dev_of_log = 0.5
lognormalvalues = np.random.lognormal(mean_of_log, std_dev_of_log, 5)
print(lognormalvalues)

[1.72724755 1.00422053 0.56809531 0.55207527 0.94114397]


In [15]:
n_trials = 10
probabilities = [0.2, 0.3, 0.5] # Probabilities of each outcome
multivalues = np.random.multinomial(n_trials, probabilities, 5)
print(multivalues)

[[3 3 4]
 [2 3 5]
 [1 4 5]
 [3 2 5]
 [2 2 6]]


# Numpy for Linear Algebra

## Complex Matrix Operations

In [16]:
lar = np.array([[1, 2], [3, 4]])

invlar = np.linalg.inv(lar)
print(invlar)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [17]:
lar1 = np.array([[2, -1], [1, 1]])

eigenvalues, eigenvectors = np.linalg.eig(lar1)
print("eigenvalues:",eigenvalues)
print("eigenvectors:",eigenvectors)

eigenvalues: [1.5+0.8660254j 1.5-0.8660254j]
eigenvectors: [[0.35355339+0.61237244j 0.35355339-0.61237244j]
 [0.70710678+0.j         0.70710678-0.j        ]]


In [19]:
lar2 = np.array([[1, 2], [3, 4], [5, 6]])

U, S, VT = np.linalg.svd(lar2)

print(U,S,VT)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]] [9.52551809 0.51430058] [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


## Linear Equations

In [20]:
A = np.array([[2, 3], [4, 5]])

b = np.array([6, 7])

x = np.linalg.solve(A, b)
print(x)

[-4.5  5. ]


# Advanced Numpy Techniques

## Masked Arrays

In [22]:
import numpy.ma as ma
temp = np.array([22.5, 23.0, -999, 24.5, -999, 26.0, 27.2, -999, 28.5])

meantemp = np.mean(temp)

print("Mean Temperature (without handling missing values):", meantemp)


mask = (temp == -999)

masktemp = ma.masked_array(temp, mask=mask)

meantemp = ma.mean(masktemp)

print("Mean Temperature (excluding missing values):", mean_temperature)

Mean Temperature (without handling missing values): -316.14444444444445
Mean Temperature (excluding missing values): 25.28333333333333


## Structured Arrays

In [25]:
dt = np.dtype([('name', 'S25'), ('age', int), ('salary', float)])

employees = np.array([('Shyam', 18, 50000.0), ('Sundhar', 25, 60000.0)], dtype=dt)

print(employees['name'][0])

print(employees['age'])

b'Shyam'
[18 25]
